/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.time.format.DateTimeFormatter;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.OperacaoPortuaria;
import model.dao.OperacaoPortuariaDAO;

/**
 *
 * @author jvito
 */
public class ListaOperacaoPortuariaJF extends javax.swing.JFrame {

    OperacaoPortuariaDAO dao;

    /**
     * Creates new form ListaVendas
     */
    
    public ListaOperacaoPortuariaJF(){
        initComponents();
        dao = new OperacaoPortuariaDAO();
        loadOperacoes();
    }
    
    public void loadOperacoes(){
        DefaultTableModel modelo = (DefaultTableModel) tblOperacoes.getModel();
        modelo.setNumRows(0);
        for (OperacaoPortuaria obj : dao.listarTodas()) {
            Object[] linha = {
                obj.getId(),
                obj.getNavio(),
                obj.getCarga(),
                obj.getBerco(),
                obj.getFuncionario(),
                obj.getTipo(),
                obj.getDataHora().format(DateTimeFormatter.ISO_DATE),
            };
            modelo.addRow(linha);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOperacoes = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnInformacoes = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("jButton1");

        jButton4.setText("jButton1");

        jButton5.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblOperacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Navio", "Carga", "Berço", "Funcionário", "Tipo", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOperacoes);
        if (tblOperacoes.getColumnModel().getColumnCount() > 0) {
            tblOperacoes.getColumnModel().getColumn(1).setResizable(false);
            tblOperacoes.getColumnModel().getColumn(2).setResizable(false);
            tblOperacoes.getColumnModel().getColumn(3).setResizable(false);
            tblOperacoes.getColumnModel().getColumn(4).setResizable(false);
        }

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnInformacoes.setText("Mais Informações");
        btnInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacoesActionPerformed(evt);
            }
        });

        jLabel1.setText("                                                                  Operações Portuárias");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover)
                    .addComponent(btnInformacoes))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // 1. Abrir a aplicação CadastroVendaJD
        CadastroOperacaoPortuariaJD telaOperacao = new CadastroOperacaoPortuariaJD(this, rootPaneCheckingEnabled);
        telaOperacao.setVisible(true);

        // 2. recuperar o objeto Venda
        OperacaoPortuaria novoObj = telaOperacao.getOperacao();

        // 3. Se o objeto não for null persistir no BD
        if (novoObj != null) {
            try {
                dao.persist(novoObj);
                loadOperacoes();
            } catch (Exception ex) {
                System.err.println("Erro ao salvar nova operação: " + novoObj + "\n Erro: " + ex);
            }

        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblOperacoes.getSelectedRow() != -1) {
            int row = tblOperacoes.getSelectedRow();
            Long id = (Long) tblOperacoes.getValueAt(row, 0);  
            Optional<OperacaoPortuaria> optOperacao = dao.buscarPorId(id); 

            CadastroOperacaoPortuariaJD telaEdicao = new CadastroOperacaoPortuariaJD(this, rootPaneCheckingEnabled);
            telaEdicao.setOperacao(optOperacao.get());
            telaEdicao.setVisible(true);

                try {
                    dao.persist(telaEdicao.getOperacao());
                    JOptionPane.showMessageDialog(rootPane, "Operação atualizada com sucesso!");
                } catch (Exception ex) {
                    System.err.println("Erro ao editar operação\nErro: " + ex);
                    JOptionPane.showMessageDialog(rootPane, "Erro ao salvar alterações da operação.");
                }

                loadOperacoes();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Selecione uma operação");
            }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (tblOperacoes.getSelectedRow() != -1) {
            int row = tblOperacoes.getSelectedRow();
            Long id = (Long) tblOperacoes.getValueAt(row, 0);  
            Optional<OperacaoPortuaria> optOperacao = dao.buscarPorId(id); 

            if (optOperacao.isPresent()) {
                OperacaoPortuaria op = optOperacao.get();
                int oper = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente remover esta operação?");
                if (oper == JOptionPane.YES_OPTION) {
                    try {
                        dao.remover(op);
                        JOptionPane.showMessageDialog(rootPane, "Operação removida com sucesso!");
                        loadOperacoes();
                    } catch (Exception ex) {
                        System.err.println("Erro ao remover Operação\nErro: " + ex);
                        JOptionPane.showMessageDialog(rootPane, "Erro ao remover Operação.");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Operação não encontrada.");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma Operação para remover.");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacoesActionPerformed
        if (tblOperacoes.getSelectedRow() != -1) {
            int row = tblOperacoes.getSelectedRow();
            Long id = (Long) tblOperacoes.getValueAt(row, 0);  
            Optional<OperacaoPortuaria> optOperacao = dao.buscarPorId(id); 
   
            if (optOperacao.isPresent()) {
                OperacaoPortuaria o = optOperacao.get();
                String info = String.format("""
                ID: %d
                Navio: %s
                Carga: R$ %s
                Berço: %d
                Funcionário: %s
                Tipo: %s
            """,
                o.getId(),
                o.getNavio().getNome(),
                o.getCarga().getDescricao(),
                o.getBerco().getNumero(),
                o.getFuncionario().getNome(),
                o.getTipo()
                );
                JOptionPane.showMessageDialog(rootPane, info);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Venda não encontrada.");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma venda para ver as informações.");
        }
    }//GEN-LAST:event_btnInformacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaOperacaoPortuariaJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaOperacaoPortuariaJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaOperacaoPortuariaJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaOperacaoPortuariaJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaOperacaoPortuariaJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnInformacoes;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOperacoes;
    // End of variables declaration//GEN-END:variables
}
